<?xml version="1.0" encoding="utf-8"?><Database Name="DBManageContacts" Class="DBManageContactDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-T9B7LQ1\SQLEXPRESS;Initial Catalog=DBManageContacts;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DBManageContactsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Contact" Member="Contacts">
    <Type Name="Contact">
      <Column Name="IDContact" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDCustomer" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ContactName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDNetworkOperator" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDPosition" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDAddress" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Address_Contact" Member="Address" ThisKey="IDAddress" OtherKey="IDAddress" Type="Address" IsForeignKey="true" />
      <Association Name="Customer_Contact" Member="Customer" ThisKey="IDCustomer" OtherKey="IDCustomer" Type="Customer" IsForeignKey="true" />
      <Association Name="NetworkOperator_Contact" Member="NetworkOperator" ThisKey="IDNetworkOperator" OtherKey="IDNetworkOperator" Type="NetworkOperator" IsForeignKey="true" />
      <Association Name="Position_Contact" Member="Position" ThisKey="IDPosition" OtherKey="IDPosition" Type="Position" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="IDAccount" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Account_Admin" Member="Admins" ThisKey="IDAccount" OtherKey="IDAccount" Type="Admin" />
      <Association Name="Account_Customer" Member="Customers" ThisKey="IDAccount" OtherKey="IDAccount" Type="Customer" />
    </Type>
  </Table>
  <Table Name="dbo.Address" Member="Addresses">
    <Type Name="Address">
      <Column Name="IDAddress" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AddressName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="AddressAmount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IndexCustomer" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Address_Contact" Member="Contacts" ThisKey="IDAddress" OtherKey="IDAddress" Type="Contact" />
    </Type>
  </Table>
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="IDAdmin" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AdminName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="IDAccount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Account_Admin" Member="Account" ThisKey="IDAccount" OtherKey="IDAccount" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="IDCustomer" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="IDAccount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Customer_Contact" Member="Contacts" ThisKey="IDCustomer" OtherKey="IDCustomer" Type="Contact" />
      <Association Name="Account_Customer" Member="Account" ThisKey="IDAccount" OtherKey="IDAccount" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NetworkOperator" Member="NetworkOperators">
    <Type Name="NetworkOperator">
      <Column Name="IDNetworkOperator" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NetworkOperatorName" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="NetworkOperatorAmount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IndexCustomer" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="NetworkOperator_Contact" Member="Contacts" ThisKey="IDNetworkOperator" OtherKey="IDNetworkOperator" Type="Contact" />
    </Type>
  </Table>
  <Table Name="dbo.Position" Member="Positions">
    <Type Name="Position">
      <Column Name="IDPosition" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PositionName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PositionAmount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IndexCustomer" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Position_Contact" Member="Contacts" ThisKey="IDPosition" OtherKey="IDPosition" Type="Contact" />
    </Type>
  </Table>
</Database>